### ISSUE TITLE
DLL Inject Problem

### ISSUE THREAD

**Issue by HallofFameClient** [rft0/km-dll-mapper#2]
![image](https://github.com/user-attachments/assets/93ebbc31-a76a-4dd0-81a0-a0614db88184)
![image](https://github.com/user-attachments/assets/cc2e12e7-42e2-4cc7-b36a-6fc2be6f0408)

if i inject in vrchat.exe get i: [+] Hook address: 0x0000000000000000
(vrchat use easy anti cheat but free one)

**Comment by rft0** [comment]
your game probably doesn't use TranslateMessage in this case just find a frequently called function in game and pass it as hook address instead of iat walking
